CREATE SCHEMA formation;

CREATE TABLE formation.VIN (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	chateau VARCHAR(100) NOT NULL,
	appellation VARCHAR(100),
	prix DECIMAL(10,2));

CREATE SEQUENCE formation.vin_id_seq start with 1 increment 1;

CREATE TABLE formation.TRACE (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	idep VARCHAR(10),
	time TIMESTAMP NOT NULL,
	url_serveur VARCHAR(100) NOT NULL,
	endpoint VARCHAR(200) NOT NULL,
	method VARCHAR(10) NOT NULL,
	request_header_accept VARCHAR(200),
	request_header_user_agent VARCHAR(200),
	response_status CHAR(3),
	response_header_content_type VARCHAR(100),
	response_header_content_length INT,
	time_taken INT NOT NULL
);

CREATE SEQUENCE formation.trace_id_seq start with 1 increment 1;